
# Advance operation with Business examples

In [1]:
import numpy as np
import matplotlib.pyplot as ptl

In [21]:
# Data Structure = [restaurant_id, 2021, 2022, 2023, 2024]
sales_data =np.array([
    [1, 150000, 180000, 220000, 250000], # Paradise Biryani
    [2, 200000, 140000, 160000, 190000], # Beijing Bites
    [3, 120000, 210000, 260000, 300000], # Pizza Hub
    [4, 180000, 230000, 240000, 270000], # Burger Point
    [5, 160000, 185000, 205000, 300000] # Chai Point
])

print("==== Zomato Sales Analysis ====")
print(f"Sales data shape: {sales_data.shape}")

==== Zomato Sales Analysis ====
Sales data shape: (5, 5)


In [10]:
print(f"Sales data for 1st 3 restaurant: {sales_data[ : 3]}")

Sales data for 1st 3 restaurant: [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


### Can remove resturant_id with slicing

In [11]:
print(f"Restaurant data without id: {sales_data[:, 1:]}")

Restaurant data without id: [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


### Total Sales per year

In [15]:
print(f"Total sales per year: {np.sum(sales_data, axis=0)}") # calc sum column wise

yearly_sales = np.sum(sales_data[:, 1:], axis=0) # calc sum of sales col wise without restaurant id

print(yearly_sales)

Total sales per year: [     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]


### Calculate minimum sales per restaurant

In [19]:
min_sale = np.min(sales_data[:, 1:], axis=1)
print(f"Minimum sales per restaurant: {min_sale}")

Minimum sales per restaurant: [150000 120000 200000 180000 160000]


### Calculate maximum sales per year

In [22]:
max_sales = np.max(sales_data[:, 1:], axis=0)
print(f"Maximum sales per year: {max_sales}")

Maximum sales per year: [200000 230000 260000 300000]


### Calculate average sales per restaurant

In [23]:
avg_sales = np.average(sales_data[:, 1:], axis=1)
print(f"Average sales per restaurant: {avg_sales}")

Average sales per restaurant: [200000. 172500. 222500. 230000. 212500.]
