## Operations on Array

In [2]:
import numpy as np

### Slicing and Sorting On 1D Array or Vector

In [21]:
arr = np.array([1, 5, 2, 3, 5, 4, 6, 1, 9, 7, 4, 8])
print(arr)
print(arr[2 : 8]) # Index 8 is not inclusive
print(arr[0: ])
print(arr[: 6]) # Index 6 is not inclusive
print(arr[-9: -3]) # Negative indexing
print(arr[::-1]) # Reverse an array

# Sorting
print(f"Sorted Array: {np.sort(arr)}")


[1 5 2 3 5 4 6 1 9 7 4 8]
[2 3 5 4 6 1]
[1 5 2 3 5 4 6 1 9 7 4 8]
[1 5 2 3 5 4]
[3 5 4 6 1 9]
[8 4 7 9 1 6 4 5 3 2 5 1]
Sorted Array: [1 1 2 3 4 4 5 5 6 7 8 9]


### Slicing and Sorting On 2D array or Matrix

In [3]:
arr_2D = np.array([[1, 2, 6, 2],
                   [4, 3, 1, 2],
                   [5, 1, 2, 3],
                   [2, 3, 1, 9]])
print(f"Specific Element: {arr_2D[0, 1]}")
print(f"Specific Element: {arr_2D[2, 3]}")
print(f"Entire row: {arr_2D[1]}") # Prints entire row
print(f"Entire Column: {arr_2D[:, 2]}") # Prints entire column

# Sorting
print(f"Sorted 2D Array by row: {np.sort(arr_2D, axis=1)}") # Row wise sorting
print(f"Sorted 2D Array by column: {np.sort(arr_2D, axis=0)}") # Column wise sorting


Specific Element: 2
Specific Element: 3
Entire row: [4 3 1 2]
Entire Column: [6 1 2 1]
Sorted 2D Array by row: [[1 2 2 6]
 [1 2 3 4]
 [1 2 3 5]
 [1 2 3 9]]
Sorted 2D Array by column: [[1 1 1 2]
 [2 2 1 2]
 [4 3 2 3]
 [5 3 6 9]]


## Filtering in numpy array

In [5]:
nums = np.array([1, 4, 9, 3, 5, 2, 8, 1, 7, 3, 4, 8, 6, 9, 5])

even_nums = nums[nums % 2 == 0]
print(f"Even numbers are in nums: {even_nums}")

Even numbers are in nums: [4 2 8 4 8 6]


### Filter with mask

In [6]:
mask = nums > 4
print(f"Numbers greater than 4: {nums[mask]}")

Numbers greater than 4: [9 5 8 7 8 6 9 5]


### Indices and Where()

In [18]:
indices = [1, 5, 7, 9, 13]
print(f"Numbers are at \n{indices} : \n{nums[indices]}")

# Where
where_res = np.where(nums % 2 != 0)
# print(f"Odd numbers in the array nums: {where_res}") # It prints with array itself
print(f"Odd numbers in the array nums: {nums[where_res]}") # It prints with array itself

Numbers are at 
[1, 5, 7, 9, 13] : 
[4 2 1 3 9]
Odd numbers in the array nums: [1 9 3 5 1 7 3 9 5]


### where(condition, x, y)

In [22]:
my_nums = np.array([2, 1, 5, 6, 3, 8, 4, 9, 3, 7, 1])

res = np.where(my_nums > 4, my_nums ** 2, my_nums ** 3)
print(res)

[ 8  1 25 36 27 64 64 81 27 49  1]


### Arrays Concatenation

In [7]:
arr1 = np.array([1, 3, 5, 7])
arr2 = np.array([2, 4, 6, 8])

# print(arr1 + arr2) # This statement adds the elements of the arrays

print(np.concatenate((arr1, arr2))) # This statement concat the arrays


[1 3 5 7 2 4 6 8]


### Compatibility Check

In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 3, 9])
c = np.array([2, 1, 8, 7])

print(f"Compatibility: {a.shape == b.shape}") # True
print(f"Compatibility: {b.shape == c.shape}") # False

Compatibility: True
Compatibility: False


### Add Row in existing array

In [11]:
org = np.array([[1, 2, 3], [4, 5, 6]])

# np.vstack() does not modify org. It creates a new NumPy array containing the original data plus the new row.
new_row_array = np.vstack((org, [7, 8, 9]))

print(f"Original Array:\n{org}")
print(f"\nAdd new row:\n{new_row_array}")

Original Array:
[[1 2 3]
 [4 5 6]]

Add new row:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Add new Column in existing array


In [12]:
# np.hstack() does not modify org. It creates a new NumPy array containing the original data plus the new col.
new_col_array = np.hstack((org, [[77], [88]]))
print(f"Original Array:\n{org}")
print(f"\nAdd new column:\n{new_col_array}")

Original Array:
[[1 2 3]
 [4 5 6]]

Add new column:
[[ 1  2  3 77]
 [ 4  5  6 88]]


### Delete Operation on 1D Array

In [7]:
np_arr = np.array([15, 45, 32, 64, 25, 9, 77, 40])
deleted_arr = np.delete(np_arr, 2) # Returns a new array after deleting the element
# deleted_arr = np.delete(np_arr, np.arange(1, 6, 2)) # Delete the range of the array with start : stop : step
print(f"Array After deletion: {deleted_arr}")



Array After deletion: [15 45 64 25  9 77 40]
