# Numpy File save, Load Operations

In [1]:
import numpy as np
import matplotlib.pyplot as ptl

In [2]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr2 = np.zeros((3, 4))
arr3 = np.full((4, 6), 3)


### 1. Save arrays as files

In [4]:
np.save("array-1.npy", arr1)
np.save("array-2.npy", arr2)
np.save("array-3.npy", arr3)

### 2. Load files as arrays

In [7]:
loaded_arr1 = np.load('array-1.npy')
loaded_arr2 = np.load('array-2.npy')
loaded_arr3 = np.load('array-3.npy')

print("\n", loaded_arr1)
print("\n", loaded_arr2)
print("\n", loaded_arr3)


 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]]
