## Numpy Array and Basics
Learn about numpy with chai aur code

In [6]:
import numpy as np
import time

### Creating array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D array: {arr_1d}")

arr_2d = np.array([[10, 20, 30], [100, 200, 300]])
print(f"2D array: {arr_2d}")

1D array: [1 2 3 4 5]
2D array: [[ 10  20  30]
 [100 200 300]]


## Comparison between Python List and NumPy Array

In [5]:
py_list = [1, 2, 3]
print("Python list multiplication")
print(py_list * 2)

print()

np_arr = np.array([1, 2, 3]) # element wise multiplication
print("NumPy array multiplication")
print(np_arr * 2)

Python list multiplication
[1, 2, 3, 1, 2, 3]

NumPy array multiplication
[2 4 6]


In [7]:
start = time.time()
my_list = [i * 2 for i in range(1000000)]
print(f"List operation time {time.time() - start}")

start = time.time()
my_arr = np.arange(1000000) * 2
print(f"NumPy Array operation time {time.time() - start}")

List operation time 0.040407657623291016
NumPy Array operation time 0.0032181739807128906


### Creating array from scratch


### All Zero Element array
Inside zeros method we can use list [], or tuple ()

In [9]:
zeros_arr = np.zeros([2, 3])
print(f"Zeros Array: \n {zeros_arr}")

Zeros Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]


### All Ones Element array
Inside ones method we can use list [], or tuple ()

In [12]:
ones_arr = np.ones((3, 3))
print(f"Ones Array: \n {ones_arr}")

Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Full Array with all 10
Inside full method we can use list [], or tuple ()

In [15]:
full_arr = np.full((2, 4), 10)
print(f"Full Array with all 10 elements: \n {full_arr}")

Full Array with all 10 elements: 
 [[10 10 10 10]
 [10 10 10 10]]


### All Random Element
Inside random method we can use list [], or tuple ()

In [8]:
random_matrix = np.random.random((2, 3))
print(f"Random Elements Matrix: \n {random_matrix}")

Random Elements Matrix: 
 [[0.19966437 0.81383325 0.76838271]
 [0.34224136 0.60775896 0.87701429]]


### Sequence of numbers



##### Print even numbers up to n

In [21]:
print("Program to print even numbers up to n in numpy")
n = int(input("Enter a number: "))
even = np.arange(2, n + 1, 2)
print(even)

Program to print even numbers up to n using in numpy
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


#### Print odd numbers up to n


In [22]:
print("Program to print odd numbers up to n in numpy")
n = int(input("Enter a number: "))
odd = np.arange(1, n + 1, 2)
print(odd)

Program to print odd numbers up to n in numpy
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


## Vector, Matrix and Tensor

### 1. Vector or 1D Array

In [26]:
vector = np.array([1, 2, 3, 4, 5])
print(f"Vector: {vector}")

Vector: [1 2 3 4 5]


### 2. Matrix or 2D Array

In [28]:
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])

print(f"Matrix: {matrix}")

Matrix: [[1 2 3]
 [4 5 6]]


### 3. Tensor or 3D+ Array

In [30]:
tensor = np.array([
                [[1, 2], [3, 4]],
                [[5, 6], [7, 9]],
                [[10, 11], [12, 13]]
                ])

print(tensor)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  9]]

 [[10 11]
  [12 13]]]


### Arrays Property

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Dimensions {arr.ndim}")
print(f"Shape of the array is: {arr.shape}")
print(f"Size of the array is: {arr.size}")
print(f"Data type of the array is: {arr.dtype}")
print(f"Items size is: {arr.itemsize} bytes")
print(f"Total Memory (Bytes) : {arr.nbytes}")
print(f"Flattened array: {arr.flatten()}")
print(f"Transposed array: {arr.T}")
print(f"Flags: {arr.flags}")
print(f"Strides: {arr.strides}")

Dimensions 2
Shape of the array is: (2, 3)
Size of the array is: 6
Data type of the array is: int64
Items size is: 8 bytes
Total Memory (Bytes) : 48
Flattened array: [1 2 3 4 5 6]
Transposed array: [[1 4]
 [2 5]
 [3 6]]
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Strides: (24, 8)


### Array Reshaping

In [10]:
new_arr = np.arange(1, 10)
print(f"Original Array: {new_arr}")
# [1, 2, 3, 4, 5, 6, 7, 8, 9]

reshaped_arr = new_arr.reshape(3, 3)
print(f"Reshaped Array: {reshaped_arr}")

ravel = arr.ravel()
print(f"Raveled Array: {ravel}")


Original Array: [1 2 3 4 5 6 7 8 9]
Reshaped Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Raveled Array: [1 2 3 4 5 6]
